import type { SiteConfig } from '../types/narrative'

export const siteConfig: SiteConfig = {
  locale: 'id',
  siteTitle: 'Narasi Kota Khatulistiwa',
  brand: { name: 'Khatulistiwa', edition: 'JURNAL PERJALANAN · 2026' },

  hero: {
    kicker: 'JURNAL PERJALANAN · KALIMANTAN BARAT',
    title: 'Narasi Kota Khatulistiwa',
    statement:
      'Di garis lintang nol derajat, matahari berdiri tegak di atas kepala dan sebuah kota tumbuh dari pertemuan sungai, rempah, dan tiga peradaban. Inilah Pontianak — dibaca perlahan, dari fajar hingga senja.',
    scrollLabel: 'Mulai telusuri kisah kota',
    coordinates: `0°02'46.0" LS · 109°19'20.0" BT`,
    image: {
      src: '/media/hero-kapuas-dawn.png',
      alt: 'Fajar keemasan di atas Sungai Kapuas dengan siluet kubah masjid dan perahu kayu di kejauhan',
      position: '50% 42%',
    },
    video: '/media/hero-kapuas.mp4',
    audio: 'kapuas',
  },

  transitions: [
    { id: 't1', theme: 'mist-dew', badge: '01 • Titian Fajar', caption: 'Kabut pagi tersibak dari permukaan Kapuas' },
    { id: 't2', theme: 'borneo-jungle', badge: '02 • Jalinan Hayat', caption: 'Akar-akar rimba menjalin tiga peradaban' },
    { id: 't3', theme: 'kapuas-waters', badge: '03 • Riak Alir Kapuas', caption: 'Riak sungai mengalir menuju senja' },
    { id: 't4', theme: 'coffee-spice', badge: '04 • Ceret & Rempah', caption: 'Uap ceret tembaga dan bara sangrai kopi' },
  ],

  chapters: [
    {
      id: 'suaka',
      index: 'I',
      badge: '01 • Titian Fajar',
      gate: 'Memasuki Suaka I',
      title: 'Titik Temu Kubah & Menara',
      summary:
        'Kubah emas Masjid Raya Mujahidin dan menara Katedral Santo Yosef menjadi dua pilar spiritualitas di jantung kota — dua bahasa doa yang berbagi langit Pontianak.',
      coordinates: `0°01'46.6" LS · 109°19'30.0" BT`,
      image: {
        src: '/masjid-raya-mujahidin-2026.jpg',
        alt: 'Kemegahan Masjid Raya Mujahidin Pontianak dengan kubah emas bertingkat dan menara tinggi di bawah langit biru',
        position: '50% 50%',
      },
      lede: 'Pagi di Pontianak dimulai bukan oleh satu suara, melainkan dua. Dari menara Masjid Raya Mujahidin, azan subuh mengalir di atas atap-atap kota; di koridor kota lainnya, lonceng Katedral Santo Yosef menyambut hari Minggu dengan dentang yang tenang. Keduanya tidak pernah bersaing — mereka bergiliran menjaga langit yang sama.',
      paragraphs: [
        'Masjid Raya Mujahidin, dengan kubah besarnya yang memantulkan cahaya Kapuas, berdiri sebagai salah satu masjid termegah di Kalimantan Barat. Di dalamnya, cahaya pagi jatuh melalui kisi-kisi, membentuk pola yang diam-diam menenun dirinya sendiri di atas lantai.',
        'Berdiri di pusat denyut kota yang sama, Katedral Santo Yosef menyimpan keheningan yang berbeda namun setara — kayu belian tua, kaca patri yang meredam matahari khatulistiwa, dan aroma dupa yang tipis. Kedua bangunan ini tidak berdiri sebagai monumen toleransi yang dibuat-buat; mereka sekadar saksi dari kebiasaan lama kota ini: berdampingan.',
        'Warga Pontianak menyebut keterhubungan keduanya bukan sekadar bentang jarak, melainkan untaian cerita. Di antara kubah dan menara itu mengalir pasar, sekolah, dan warung kopi — ruang-ruang hidup yang membuat perbedaan terasa seperti variasi, bukan jurang.',
      ],
      quote: 'Di kota ini, langit tidak dibagi. Ia dipinjam bersama, lalu dikembalikan pada senja.',
      quoteAttribution: 'Catatan tepian, subuh pertama',
      marginalia: [
        {
          heading: 'Kayu belian',
          text: 'Belian atau kayu ulin — kayu besi Kalimantan — dipakai pada rangka masjid dan gereja tua Pontianak; seratnya mengeras oleh waktu, konon tahan seabad lebih.',
        },
        {
          heading: 'Harmoni Kota',
          text: 'Masjid Raya Mujahidin dan Katedral Santo Yosef sama-sama menjadi ikon di pusat Pontianak, terhubung oleh koridor jalan utama yang merekatkan kehidupan warga.',
        },
      ],
      locations: ['mujahidin', 'katedral'],
      gallery: [
        {
          id: 'katedral-gallery',
          name: 'Gereja Katedral Santo Yosef',
          category: 'Wisata Religi',
          highlight: 'Arsitektur Neoklasik Romawi & Ornamen Ukir Kayu Ulin Dayak',
          description:
            'Gereja katedral agung dengan menara lonceng kembar megah, deretan kaca patri artistik warna-warni, serta perpaduan arsitektur Romawi kuno dan relief ukiran kayu belian khas Dayak.',
          image: '/katedral-santo-yosef-2026.jpg',
          mapsUrl: 'https://www.google.com/maps/dir/?api=1&destination=-0.0269,109.336',
        },
        {
          id: 'mujahidin-gallery',
          name: 'Masjid Raya Mujahidin',
          category: 'Wisata Religi',
          highlight: 'Kubah Emas Bertingkat & Menara 60 Meter Ikonik',
          description:
            'Masjid terbesar dan termegah di Kalimantan Barat yang mampu menampung belasan ribu jamaah, berarsitektur modern dengan pilar-pilar kokoh serta kubah bertingkat yang anggun di pusat kota.',
          image: '/masjid-raya-mujahidin-2026.jpg',
          mapsUrl: 'https://www.google.com/maps/dir/?api=1&destination=-0.0296,109.325',
        },
      ],
      audio: 'kapuas',
    },
    {
      id: 'jalinan',
      index: 'II',
      badge: '02 • Jalinan Hayat',
      gate: 'Menyusuri Akar II',
      title: 'Tiga Pilar Satu Peradaban',
      summary:
        'Dayak, Melayu, dan Tionghoa tidak sekadar hidup berdampingan di Pontianak — mereka menjalin diri seperti akar rimba: berbeda arah, satu tanah.',
      coordinates: `0°02'02.0" LS · 109°20'45.6" BT`,
      image: {
        src: '/media/bab2-budaya.png',
        alt: 'Rumah betang Dayak dan kelenteng Tionghoa dalam satu bentang budaya Kalimantan',
        position: '50% 45%',
      },
      lede: 'Kota ini didirikan di atas kesepakatan tiga sungai dan tiga bangsa. Orang Dayak turun dari hulu membawa sapeh dan mandau, orang Melayu membuka kesultanan di tepi muara, dan para perantau Tionghoa menanam kedai serta kelenteng di sela-selanya. Dua setengah abad kemudian, jalinan itu belum juga kendor.',
      paragraphs: [
        'Di Rumah Radakng, rumah betang terpanjang di negeri ini, balok-balok belian menyimpan arsitektur komunal Dayak: satu atap untuk banyak keluarga, satu tangga untuk semua. Panjangnya bukan kesombongan, melainkan pernyataan — bahwa rumah bisa menjadi bentuk lain dari hutan yang melindungi.',
        'Di Kampung Beting, Keraton Kadriah berdiri megah di persimpangan muara Sungai Kapuas dan Landak. Didirikan pada 1771 oleh Sultan Syarif Abdurrahman Al-Qadrie, istana kayu ulin berwarna kuning gading ini menyimpan meriam kuno, singgasana bersepuh emas, dan Al-Quran tulisan tangan sultan.',
        'Di pecinan tua, kelenteng Vihara Bodhisatva Karaniya Metta bernapas bersama dupa setiap pagi sejak 1673 M di tepian Dermaga Senghie. Saat Cap Go Meh tiba, jalanan kota berubah menjadi sungai barongsai dan tatung; warga dari segala asal-usul berdiri di tepi yang sama, menadahkan kamera dan doa.',
        'Dan di antara ketiganya, sentra tenun corak insang Kesultanan Kadriah menuliskan geometrinya yang sabar — garis-garis diagonal yang konon meniru insang ikan sungai, motif takbenda yang hanya lahir di kota yang hidup dari air.',
      ],
      quote: 'Akar tidak bertanya akar lain hendak ke mana. Mereka cukup saling menahan tanah agar tidak runtuh.',
      quoteAttribution: 'Petuah tepian Kapuas',
      marginalia: [
        {
          heading: 'Corak insang',
          text: 'Motif tenun khas Kesultanan Kadriah Pontianak — diagonal rapat meniru insang ikan Kapuas; dulu ditenun untuk busana para bangsawan kesultanan.',
        },
        {
          heading: 'Tatung',
          text: 'Tradisi Cap Go Meh Pontianak termasuk yang terbesar di Asia Tenggara; puluhan ribu orang memadati jalan setiap tahunnya.',
        },
        {
          heading: 'Keraton Kadriah',
          text: 'Istana kayu belian yang dibangun tahun 1771 di pertemuan muara Kapuas dan Landak, titik awal sejarah berdirinya Kota Pontianak.',
        },
      ],
      locations: ['radakng', 'kelenteng', 'kadriah', 'insang'],
      gallery: [
        {
          id: 'radakng-gallery',
          name: 'Rumah Betang Radakng',
          category: 'Cagar Budaya Dayak',
          highlight: 'Rumah Adat Terpanjang 138 Meter di Indonesia',
          description:
            'Replika rumah adat suku Dayak Kanayatn terbesar di Indonesia yang ditopang tiang-tiang kayu ulin raksasa, pusat pagelaran seni dan Pekan Gawai Dayak tahunan.',
          image: '/rumah-radakng.png',
          mapsUrl: 'https://www.google.com/maps/dir/?api=1&destination=-0.0339,109.346',
        },
        {
          id: 'kadriah-gallery',
          name: 'Keraton Kadriah Kesultanan Pontianak',
          category: 'Cagar Budaya Melayu',
          highlight: 'Istana Kayu Belian Sejak 1771 M & Titik Muara Kapuas',
          description:
            'Istana kayu ulin peninggalan Sultan Syarif Abdurrahman Al-Qadrie berwarna kuning gading, menyimpan meriam kuno, singgasana bersepuh emas, dan Al-Quran kuno.',
          image: '/keraton-kadriah.png',
          mapsUrl: 'https://www.google.com/maps/dir/?api=1&destination=-0.0275,109.3444',
        },
        {
          id: 'kelenteng-gallery',
          name: 'Vihara Bodhisatva Karaniya Metta',
          category: 'Cagar Budaya Tionghoa',
          highlight: 'Tempat Ibadah Bersejarah Tertua Sejak 1673 M di Tepian Senghie',
          description:
            'Kelenteng tertua di Pontianak yang telah berdiri di tepi muara Kapuas bahkan sebelum Kesultanan didirikan, saksi bisu sejarah panjang pemukiman Tionghoa.',
          image: '/klenteng-karaniya-metta.png',
          mapsUrl: 'https://www.google.com/maps/dir/?api=1&destination=-0.024,109.335',
        },
        {
          id: 'insang-gallery',
          name: 'Sentra Tenun Corak Insang Kesultanan',
          category: 'Warisan Budaya Takbenda',
          highlight: 'Kain Tenun Geometris Bernilai Historis Tinggi',
          description:
            'Kain tenun tradisional khas Melayu Pontianak dengan motif geometris diagonal yang meniru insang ikan sungai Kapuas, busana kebesaran para bangsawan masa silam.',
          image: '/media/specimen-insang.png',
          mapsUrl: 'https://www.google.com/maps/dir/?api=1&destination=-0.0288,109.3486',
        },
      ],
      audio: 'sapeh',
    },
    {
      id: 'tepian',
      index: 'III',
      badge: '03 • Riak Alir Kapuas',
      gate: 'Merengkuh Senja III',
      title: 'Denyut Tepian Kapuas',
      summary:
        'Sungai terpanjang di Nusantara tidak mengalir melewati Pontianak — Pontianaklah yang tumbuh di tepinya, dan waterfront-nya adalah beranda kota.',
      coordinates: `0°01'20.3" LS · 109°19'48.0" BT`,
      image: {
        src: '/media/bab5-waterfront.png',
        alt: 'Senja keemasan di waterfront Sungai Kapuas dengan perahu tambang dan lampu-lampu kota',
        position: '50% 55%',
      },
      lede: 'Menjelang pukul lima sore, kota ini berjalan ke arah yang sama: ke tepi sungai. Taman Alun Kapuas dan waterfront yang membentang di sepanjang sisi kota berubah menjadi ruang tamu bersama — pedagang membuka lapak, anak-anak mengejar layang-layang, dan perahu tambang mengetuk mesinnya menunggu penumpang pulang.',
      paragraphs: [
        'Sungai Kapuas mengalir sejauh 1.143 kilometer dari pegunungan di perbatasan hingga muara di laut Natuna — denyut terpanjang di kepulauan ini. Bagi Pontianak, ia bukan latar pemandangan, melainkan jalan raya pertama, pasar pertama, dan alasan kota ini berdiri.',
        'Perahu tambang — sampan bermesin kecil yang menyeberangkan warga dari kota ke Siantan — adalah kendaraan paling jujur di Pontianak. Beberapa ribu rupiah, beberapa menit, dan satu pelajaran geografi: bahwa kota ini dibelah sungai dan disatukan oleh penyeberangannya.',
        'Ketika senja benar-benar tiba, langit khatulistiwa memamerkan warnanya yang paling murah hati: jingga yang larut menjadi ungu di atas air. Lampu-lampu perahu menyala satu per satu, dan kota berbisik pelan — seolah sungai sedang menceritakan kembali hari itu kepada laut.',
      ],
      quote: 'Sungai tidak pernah pergi ke mana-mana. Ia hanya lewat, dan kota ini belajar setia dari caranya lewat.',
      quoteAttribution: 'Senja di dermaga tambang',
      marginalia: [
        {
          heading: '1.143 km',
          text: 'Panjang Sungai Kapuas — sungai terpanjang di Indonesia — membentang dari Pegunungan Müller hingga muara di Laut Natuna.',
        },
        {
          heading: 'Tambang',
          text: 'Perahu penyeberangan kayu bermesin kecil; tarifnya hanya beberapa ribu rupiah, menghubungkan kota dengan Siantan dalam hitungan menit.',
        },
      ],
      locations: ['alun-kapuas'],
      gallery: [
        {
          id: 'waterfront-gallery',
          name: 'Waterfront City & Taman Alun Kapuas',
          category: 'Tepian Kapuas',
          highlight: 'Promenade Pejalan Kaki & Pusat Rekreasi Senja Warga',
          description:
            'Taman tepian sungai dengan pemandangan terbuka menghadap Sungai Kapuas, ramai oleh warga yang bersantai, menikmati angin sungai, dan melihat perahu melintas.',
          image: '/Water-front.png',
          mapsUrl: 'https://www.google.com/maps/dir/?api=1&destination=-0.0223,109.33',
        },
      ],
      audio: 'kapuas',
    },
    {
      id: 'rasa',
      index: 'IV',
      badge: '04 • Ceret & Rempah',
      gate: 'Mengecap Rasa IV',
      title: 'Pusaka Kopi & Kuliner Legendaris',
      summary:
        'Sebelum kota bangun, ceret Asiang sudah mendidih. Sejak 1958, warung kopi tua itu menjaga sebuah ritual pagi yang tidak pernah berubah.',
      coordinates: `0°01'39.7" LS · 109°20'13.2" BT`,
      image: {
        src: '/media/bab6-kopi.png',
        alt: 'Ceret tembaga mengepul di atas arang dan segelas kopi robusta di warung kopi tua Pontianak',
        position: '50% 48%',
      },
      lede: 'Pukul lima pagi, ketika kabut Kapuas belum sepenuhnya pergi, Pak Asiang menyalakan arangnya. Di Warung Kopi Asiang — berdiri sejak 1958 di Jalan Merapi — kopi robusta disaring berkali-kali hingga pekat, lalu dituang dari ketinggian ke gelas-gelas yang sudah menunggu di meja marmer tua.',
      paragraphs: [
        'Konon jumlah gelas yang terjual di sini mencapai ribuan setiap hari, dan tidak ada dua gelas yang diseduh dengan cara berbeda. Air dari ceret tembaga, kopi dari kebun Ketapang, susu kental manis yang jatuh terakhir — sebuah formula yang dijaga seperti resep kerajaan kecil.',
        'Warung kopi di Pontianak bukan sekadar tempat minum; ia adalah parlemen rakyat. Di sinilah kabar kota diperbincangkan, dagangan diputuskan, dan perbedaan-perbedaan kota dirundingkan sambil menunggu kopi dingin. Ada yang menyebut Pontianak kota seribu warung kopi — barangkali jumlahnya melebihi itu.',
        'Dan dari meja warkop yang sama, kuliner kota mengalir keluar: pengkang bakar ketan gurih berbumbu ebi, kwetiau sapi goreng harum kuali, sup ikan asam pedas segar, hingga bubur pedas — semangkuk bubur rempah sayur daun yang menolak diberi nama biasa. Rasa-rasa ini adalah bab penutup perjalanan, sekaligus alasan untuk selalu kembali.',
      ],
      quote: 'Kopi yang baik tidak perlu diumumkan. Aromanya sendiri yang berkeliling kota lebih dulu.',
      quoteAttribution: 'Ritual pukul lima pagi, Jalan Merapi',
      marginalia: [
        {
          heading: '1958',
          text: 'Warung Kopi Asiang berdiri di Jalan Merapi sejak 1958; ceret tembaga dan saringan kainnya kini menjadi bagian dari memori kolektif kota.',
        },
        {
          heading: 'Bubur pedas',
          text: 'Bubur khas Melayu Sambas–Pontianak: nasi sangrai, rempah, dan daun kesum serta pakis — sama sekali tidak memakai cabai; "pedas" merujuk pada kehangatan rempahnya.',
        },
        {
          heading: 'Kuliner Pelengkap',
          text: 'Pengkang bakar isi ebi dibungkus daun pisang, kwetiau sapi arang, dan sup ikan asam pedas khas perairan Kapuas.',
        },
      ],
      locations: ['asiang'],
      gallery: [
        {
          id: 'asiang-gallery',
          name: 'Warung Kopi Asiang (Sejak 1958)',
          category: 'Warung Kopi Legendaris',
          highlight: 'Seduhan Kopi Robusta Saring Tarik Klasik di Meja Marmer',
          description:
            'Warkop legendaris di Jalan Merapi yang terkenal dengan sang maestro peracik kopi legendaris, menyajikan ribuan cangkir kopi pekat aromatik setiap harinya.',
          image: '/warkop-asiang.png',
          mapsUrl: 'https://www.google.com/maps/dir/?api=1&destination=-0.0277,109.337',
        },
        {
          id: 'pengkang-gallery',
          name: 'Pengkang Bakar Daun Pisang',
          category: 'Kuliner Khas Melayu',
          highlight: 'Ketan Gurih Isi Ebi Dibakar Di Atas Bara Tempurung Kelapa',
          description:
            'Ketan gurih berisi ebi yang dibungkus daun pisang berbentuk kerucut kembar dijepit bambu, disajikan hangat bersama sambal kepah yang pedas legit.',
          image: '/pengkang-bakar.jpg',
          mapsUrl: 'https://www.google.com/maps/dir/?api=1&destination=-0.0277,109.337',
        },
        {
          id: 'kwetiau-gallery',
          name: 'Kwetiau Sapi Kuali Arang Pontianak',
          category: 'Kuliner Legendaris',
          highlight: 'Aroma Asap Kuali Panas Berpadu Daging Sapi Empuk',
          description:
            'Kwetiau beras lembut yang ditumis cepat di atas kuali wajan bara api arang dengan potongan daging sapi, urat kenyal, dan sayuran segar beraroma harum menggoda.',
          image: '/kwetiau-sapi.jpg',
          mapsUrl: 'https://www.google.com/maps/dir/?api=1&destination=-0.0277,109.337',
        },
        {
          id: 'sup-ikan-gallery',
          name: 'Sup Ikan Asam Pedas Segar',
          category: 'Kuliner Khas Pesisir',
          highlight: 'Kesegaran Kuah Rempah Kunyit, Terong Asam & Ikan Segar Kapuas',
          description:
            'Sup ikan segar berkuah kuning bening dengan paduan terong asam dan rempah lokal Kalimantan, menghasilkan cita rasa asam segar yang membangkitkan selera.',
          image: '/sup-ikan-asam-pedas.jpg',
          mapsUrl: 'https://www.google.com/maps/dir/?api=1&destination=-0.0277,109.337',
        },
      ],
      audio: 'kopi',
    },
  ],

  locations: {
    mujahidin: {
      id: 'mujahidin',
      name: 'Masjid Raya Mujahidin',
      capsule: 'Masjid Raya Mujahidin',
      address: 'Jl. Jend. Ahmad Yani, Akcaya, Pontianak Selatan',
      dms: `0°01'46.6" LS · 109°19'30.0" BT`,
      lat: -0.0296,
      lng: 109.325,
      mapX: 52,
      mapY: 62,
      category: 'Wisata Religi',
      highlight: 'Kubah Emas Bertingkat & Menara 60 Meter',
    },
    katedral: {
      id: 'katedral',
      name: 'Gereja Katedral Santo Yosef',
      capsule: 'Katedral Santo Yosef',
      address: 'Jl. Patimura No.195, Pontianak Kota',
      dms: `0°01'36.8" LS · 109°20'09.6" BT`,
      lat: -0.0269,
      lng: 109.336,
      mapX: 66,
      mapY: 58,
      category: 'Wisata Religi',
      highlight: 'Perpaduan Romawi Kuno & Ukiran Ulin Dayak',
    },
    radakng: {
      id: 'radakng',
      name: 'Rumah Betang Radakng',
      capsule: 'Rumah Radakng, Kota Baru',
      address: 'Jl. Sutan Syahrir, Kompleks Perkampungan Budaya, Pontianak Kota',
      dms: `0°02'02.0" LS · 109°20'45.6" BT`,
      lat: -0.0339,
      lng: 109.346,
      mapX: 80,
      mapY: 76,
      category: 'Cagar Budaya',
      highlight: 'Rumah Adat Dayak Terpanjang 138 Meter di Indonesia',
    },
    kelenteng: {
      id: 'kelenteng',
      name: 'Vihara Bodhisatva Karaniya Metta',
      capsule: 'Vihara Karaniya Metta, Senghie',
      address: 'Jl. Kapuas Indah, Dermaga Senghie, Pontianak Kota',
      dms: `0°01'26.4" LS · 109°20'06.0" BT`,
      lat: -0.024,
      lng: 109.335,
      mapX: 62,
      mapY: 66,
      category: 'Cagar Budaya',
      highlight: 'Kelenteng Tertua Bersejarah Sejak 1673 M',
    },
    kadriah: {
      id: 'kadriah',
      name: 'Keraton Kadriah Kesultanan',
      capsule: 'Keraton Kadriah, Kampung Beting',
      address: 'Kampung Beting, Kel. Dalam Bugis, Pontianak Timur',
      dms: `0°01'39.0" LS · 109°20'40.0" BT`,
      lat: -0.0275,
      lng: 109.3444,
      mapX: 74,
      mapY: 52,
      category: 'Cagar Budaya',
      highlight: 'Istana Kayu Belian Sejak 1771 & Titik Muara Kapuas-Landak',
    },
    insang: {
      id: 'insang',
      name: 'Sentra Tenun Corak Insang',
      capsule: 'Sentra Tenun Insang, Pontianak Timur',
      address: 'Kampung Beting & Tambelan Sampit, Pontianak Timur',
      dms: `0°01'44.0" LS · 109°20'55.0" BT`,
      lat: -0.0288,
      lng: 109.3486,
      mapX: 78,
      mapY: 55,
      category: 'Cagar Budaya',
      highlight: 'Warisan Budaya Takbenda & Tenun ATBM Tradisional',
    },
    'alun-kapuas': {
      id: 'alun-kapuas',
      name: 'Taman Alun Kapuas & Waterfront',
      capsule: 'Waterfront Alun Kapuas',
      address: 'Jl. Rahadi Usman, tepian Sungai Kapuas, Pontianak Kota',
      dms: `0°01'20.3" LS · 109°19'48.0" BT`,
      lat: -0.0223,
      lng: 109.33,
      mapX: 58,
      mapY: 50,
      category: 'Tepian Kapuas',
      highlight: 'Pusat Kehidupan Tepian Sungai & Penyeberangan Sampan Tambang',
    },
    asiang: {
      id: 'asiang',
      name: 'Warung Kopi Asiang (1958)',
      capsule: 'Warkop Asiang 1958, Jl. Merapi',
      address: 'Jl. Merapi No. 15, Pontianak Kota',
      dms: `0°01'39.7" LS · 109°20'13.2" BT`,
      lat: -0.0277,
      lng: 109.337,
      mapX: 68,
      mapY: 62,
      category: 'Warung Kopi',
      highlight: 'Kopi Hainan Saring Klasik & Meja Marmer Bundar Sejak 1958',
    },
  },

  colophon: {
    quote: 'Di tepian Kapuas yang tenang, setiap arah adalah pulang.',
    note: 'Narasi Kota Khatulistiwa adalah jurnal perjalanan editorial tentang harmoni budaya, pusaka belian, denyut tepian Kapuas, dan kuliner legendaris Pontianak.',
    restartLabel: 'Kembali ke fajar Kapuas',
    credit: 'NARASI KOTA KHATULISTIWA · 2026',
  },

  copy: {
    skipToContent: 'Langsung ke isi utama',
    continueJourney: 'Lanjutkan perjalanan',
    exploreFurther: 'Menyusuri kisah selengkapnya',
    skipToNext: 'Langsung ke bab selanjutnya',
    audioHint: 'Sentuh untuk mendengarkan denyut suara kota',
    audioOn: 'Matikan suara kota',
    audioOff: 'Dengarkan suara kota',
    mapTitle: 'Peta lokasi',
    mapDirections: 'Buka petunjuk arah Google Maps',
    mapClose: 'Tutup peta',
    imageUnavailable: 'Media belum tersedia',
    locationFallback: 'Lihat di peta',
  },
}
